apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-76bu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-76bu@sha256:7fa9ffc18678444527e7dd82bd380ab29328165aa2fe7601b4534eb8225ce3c0
        name: my-nodejs
        resources: {}
status: {}
